---
- name: Generate ssh keypair
  shell: 'ssh-keygen -b 2048 -t rsa -f {{ ssh_key_path }} -q -C "" -N ""'
  args:
    creates: "{{ ssh_key_path }}"

- name: set ssh public key as fact and strip login domain
  set_fact:
    env_public_key: "{{ lookup('file', ssh_key_path + '.pub') }}"
